---
- name: "[Brocade ICX] Configure NTP servers"
  community.network.icx_config:
    lines:
      - "ntp"
      - "server {{ ntp_primary }}"
      - "server {{ ntp_secondary }}"
      - "clock timezone gmt+07"

