---
- name: "[Brocade CER/IronWare] Configure NTP servers"
  community.network.icx_config:
    lines:
      - "ntp"
      - "server {{ ntp_primary }}"
      - "server {{ ntp_secondary }}"
      - "exit"
    match: line
