---
- name: "[Brocade CER/IronWare] Configure NTP servers (legacy-SSH workaround via expect)"
  ansible.builtin.expect:
    command: >-
      ssh {{sshkey}} {{ ansible_user }}@{{ ansible_host }}
    responses:
      "[Pp]assword:\\s*$":
        - "{{ ansible_password }}"
      "[>#]\\s*$":
        - "enable"
        - "configure terminal"
        - "ntp"
        - "server {{ ntp_primary }}"
        - "server {{ ntp_secondary }}"
        - "exit"
        - "exit"
        - "exit"
        - "exit"
    timeout: 20
  changed_when: true
  delegate_to: localhost
