---
- name: "[Cumulus Linux] Set NTP VRF (NVUE, 5.15+ syntax)"
  ansible.builtin.command: "nv set system ntp vrf mgmt"
  become: true
  changed_when: true

- name: "[Cumulus Linux] Add NTP servers (NVUE, 5.15+ syntax)"
  loop:
    - "{{ ntp_primary }}"
    - "{{ ntp_secondary }}"
  ansible.builtin.command: "nv set system ntp server {{ item }}"
  become: true
  changed_when: true

- name: "[Cumulus Linux] Apply NVUE configuration"
  ansible.builtin.command: "nv config apply"
  become: true
  changed_when: true