---
- name: "[Cumulus Linux] Configure chrony NTP servers"
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    create: true
    regexp: "^server {{ item }}"
    line: "server {{ item }} iburst"
    mode: "0644"
  loop:
    - "{{ ntp_primary }}"
    - "{{ ntp_secondary }}"
  become: true

- name: "[Cumulus Linux] Restart chrony"
  ansible.builtin.systemd:
    name: chrony
    state: restarted
    enabled: true
  become: true
