---
- name: "[Cumulus Linux] Enable SNMP server (NVUE)"
  ansible.builtin.command: "nv set system snmp-server state enabled"
  become: true
  changed_when: true

- name: "[Cumulus Linux] Configure SNMP read-only community (NVUE)"
  ansible.builtin.command: "nv set system snmp-server readonly-community {{ vault_snmp_community_ro }}"
  become: true
  changed_when: true
 
#- name: "[Cumulus Linux] Configure SNMP user-name (NVUE)"
#  ansible.builtin.command: "nv set system snmp-server username {{ vault_snmp_community_ro }}"
#  become: true
#  changed_when: true

- name: "[Cumulus Linux] Configure SNMP trap destination (NVUE)"
  ansible.builtin.command: "nv set system snmp-server trap-destination {{ vault_snmp_trap_host }} vrf mgmt community-password {{ vault_snmp_community_ro }}"
  become: true
  changed_when: true

- name: "[Cumulus Linux] Apply NVUE configuration"
  ansible.builtin.command: "nv config apply -y"
  become: true
  changed_when: true
