---
- name: "[Brocade ICX] Add static routes"
  when: static_routes is defined
  loop: "{{ static_routes | default([]) }}"
  loop_control:
    label: "Route to {{ item.destination }}"
  community.network.icx_config:
    lines:
      - "ip route {{ item.destination }} {{ item.mask }} {{ item.nexthop }}"
    match: line
