---
- name: "[Brocade ICX] Enable SSH and HTTPS management"
  ansible.builtin.expect:
    command: >-
      ssh {{ icx_ssh_crypto_args }} {{ ansible_user }}@{{ ansible_host }}
    responses:
      "[Pp]assword:\\s*$":
        - "{{ ansible_password }}"
      "[>#]\\s*$":
        - "enable"
        - "configure terminal"
        - "crypto key generate rsa modulus 2048"
        - "ip ssh server enable"
        - "web-management https"
        - "exit"
        - "exit"
    timeout: 20
  changed_when: true
  delegate_to: localhost

