---
- name: "[Aruba AOS-CX] Configure local management user account"
  arubanetworks.aoscx.aoscx_user:
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    description: "Managed by Ansible"
    password_type: "plaintext"
    state: create

