---
- name: "[Aruba AOS-CX] Configure local user account"
  arubanetworks.aoscx.aoscx_config:
    lines:
      - "user {{ ansible_user }} group administrators password plaintext {{ ansible_password }}"
