---
- name: "[Brocade ICX] Configure local user account"
  ansible.builtin.expect:
    command: >-
      ssh {{ icx_ssh_crypto_args }} {{ ansible_user }}@{{ ansible_host }}
    responses:
      "[Pp]assword:\\s*$":
        - "{{ ansible_password }}"
      "[>#]\\s*$":
        - "enable"
        - "configure terminal"
        - "username {{ ansible_user }} password {{ ansible_password }}"
        - "username {{ ansible_user }} privilege 0"
        - "exit"
        - "exit"
        - "exit"
    timeout: 20
  changed_when: true
  delegate_to: localhost

