---
# Huawei CloudEngine (CE-series, datacenter) — local user account
- name: "[Huawei CE] Configure local user account"
  community.network.ce_config:
    lines:
      - "aaa"
      - "  local-user {{ ansible_user }} password irreversible-cipher {{ ansible_password }}"
      - "  local-user {{ ansible_user }} privilege level 15"
      - "  local-user {{ ansible_user }} service-type ssh"
    match: line
