---
- name: "[Brocade CER/IronWare] Configure syslog destination"
  community.network.icx_config:
    lines:
      - "logging host {{ syslog_server }}"
      - "logging facility {{ syslog_facility }}"
    match: line
