---
- name: "[Huawei S] Set interface to access mode and assign VLAN"
  community.network.ce_config:
    lines:
      - "interface {{ interface_name }}"
      - "  port link-type access"
      - "  port default vlan {{ vlan_id }}"
    match: line
